First version of solution
MorozVladislav/Python-Studying pull request #3
Opened 2017-11-27 20:20 UTC by MorozVladislav

I'm an artist. I see so)

2017-11-30 11:57 UTC, dmitry-moroz requested changes

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +    def wrapper(a, b):
1) Why are you passing to ```wrapper``` the same args ```(a, b)``` as in function ```multiply_1```? What if arguments for function have been changed? You have to change it in two places. Do you think that it's ok?
2) I suggest to name wrapped function "wrappe**d**".

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +        def wrapper_2(a, b):
1) The same as above about arguments.
2) I suggest to rename:
```
wrapper_1 -> wrapper
wrapper_2 -> wrapped
```

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +CACHE = {}
Define global variables at the top of file.

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +        self._phone_ = phone
```self._phone```
Why do you need second underscore? One enough.

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +        self.operator = operator
Please implement ```operator``` like a ```@property``` too.

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +        return "{} {} {}".format("".join(self._phone_[:4]), "".join(self._phone_[4:]), self.operator)
1) Get rid of this ```"{} {} {}"```. Use ```join```.
2) What if code is longer than 4 digits? Phone number length is always = 7.

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +            if str(args) + str(kwargs) not in CACHE[func].keys():
1) Why are you calculation this key ```str(args) + str(kwargs)``` all the time?! Why you can't do it once?
2) ```not in CACHE[func].keys()``` you don't need ```keys()``` it's enough: ```not in CACHE[func]```

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +                CACHE[func][str(args) + str(kwargs)][1] = datetime.now()
**Wtf is going here?!?!** (lines 32-35)
```
result = func(*args, **kwargs)
CACHE[func][key] = (result, datetime.now())
return result
```

2017-11-30 11:57 UTC, dmitry-moroz commented on solutions/task_3.py
> +            if (datetime.now() - CACHE[func][str(args)+str(kwargs)][1]).total_seconds() < cache_life_time:
To not use ```.total_seconds()``` use ```time.time()``` to get Unix time, datetime lib is for more complex things.

2017-11-30 12:08 UTC, dmitry-moroz commented on solutions/task_3.py
> +            CACHE[func][str(args)+str(kwargs)][0] = func(*args, **kwargs)
Do you know construction?
```
if ... :
    ...
else:
    ...
```

2017-11-30 18:07 UTC, MorozVladislav commented on solutions/task_3.py
> +    def wrapper(a, b):
Agree. Fixed.

2017-11-30 18:09 UTC, MorozVladislav commented on solutions/task_3.py
> +        def wrapper_2(a, b):
Agree. Fixed.

2017-11-30 18:10 UTC, MorozVladislav commented on solutions/task_3.py
> +CACHE = {}
Fixed.

2017-11-30 18:16 UTC, MorozVladislav commented on solutions/task_3.py
> +            if str(args) + str(kwargs) not in CACHE[func].keys():
Agree. Fixed.

2017-11-30 18:18 UTC, MorozVladislav commented on solutions/task_3.py
> +                CACHE[func][str(args) + str(kwargs)][1] = datetime.now()
Sorry. I was young and drunk.

2017-11-30 18:29 UTC, MorozVladislav commented on solutions/task_3.py
> +        self._phone_ = phone
Fixed.

2017-11-30 18:32 UTC, MorozVladislav commented on solutions/task_3.py
> +        self.operator = operator
Done.

2017-11-30 18:44 UTC, MorozVladislav commented on solutions/task_3.py
> +        return "{} {} {}".format("".join(self._phone_[:4]), "".join(self._phone_[4:]), self.operator)
Fixed.

2017-11-30 18:47 UTC, MorozVladislav commented on solutions/task_3.py
> +            CACHE[func][str(args)+str(kwargs)][0] = func(*args, **kwargs)
Fixed.

2017-12-05 08:27 UTC, dmitry-moroz requested changes

2017-12-05 08:27 UTC, dmitry-moroz commented on solutions/task_3.py
> +        return "".join("".join(self._phone[:-7]) + " " + "".join(self._phone[-7:]) + " " + self.operator)
Omg...
Please. Tell. Me. What. This. Code. Is. Doing? What. Is. Sense. Do. You. See. Here?
How are you able to write such code?
```
Hmmm... I have a string '1234567'
How can I convert it to the same string? Idea!
I can split it into chars -> ['1', '2', '3', '4', '5', '6', '7']
And join all of them with empty string!! "".join(['1', '2', '3', '4', '5', '6', '7'])
Great! I have got the same string '1234567'!
```

2017-12-05 08:27 UTC, dmitry-moroz commented on solutions/task_3.py
> +                return CACHE[func][key][0]
If you will improve this code (lines 39-41) you will get the same code as above:
```
CACHE[func][key] = [func(*args, **kwargs), time.time()]
return CACHE[func][key][0]
```
Would you like to improve this moment? (I suppose yes)

2017-12-05 08:27 UTC, dmitry-moroz commented on solutions/task_3.py
> +            key = str(args) + str(kwargs)
Why you don't rename your ```wrapper_1``` and ```wrapper_2``` as above?
Why I have to write the same comments twice? You have to apply all the comments from PR to all the code, isn't it?

2017-12-10 07:36 UTC, merged